// Generated by `npx supabase gen types typescript --local > src/lib/database.types.ts`.
// Regenerate after every schema-bearing migration; never hand-edit.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      app_settings: {
        Row: {
          description: string | null;
          key: string;
          updated_at: string;
          updated_by: string | null;
          value: NonNullable<Json>;
        };
        Insert: {
          description?: string | null;
          key: string;
          updated_at?: string;
          updated_by?: string | null;
          value: NonNullable<Json>;
        };
        Update: {
          description?: string | null;
          key?: string;
          updated_at?: string;
          updated_by?: string | null;
          value?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "app_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "app_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          action: string;
          actor_id: string | null;
          created_at: string;
          id: number;
          new_data: Json | null;
          old_data: Json | null;
          row_id: string | null;
          table_name: string;
        };
        Insert: {
          action: string;
          actor_id?: string | null;
          created_at?: string;
          id?: never;
          new_data?: Json | null;
          old_data?: Json | null;
          row_id?: string | null;
          table_name: string;
        };
        Update: {
          action?: string;
          actor_id?: string | null;
          created_at?: string;
          id?: never;
          new_data?: Json | null;
          old_data?: Json | null;
          row_id?: string | null;
          table_name?: string;
        };
        Relationships: [];
      };
      blood_requests: {
        Row: {
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          cancel_reason: string | null;
          closed_at: string | null;
          component: string | null;
          created_at: string;
          created_by: string;
          current_tier: Database["public"]["Enums"]["request_tier"];
          district_id: number;
          id: string;
          is_emergency: boolean;
          notes: string | null;
          patient_id: string;
          published_at: string | null;
          required_at: string;
          status: Database["public"]["Enums"]["request_status"];
          tier_changed_at: string | null;
          treating_centre: string;
          units_needed: number;
          updated_at: string;
        };
        Insert: {
          area?: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          cancel_reason?: string | null;
          closed_at?: string | null;
          component?: string | null;
          created_at?: string;
          created_by: string;
          current_tier?: Database["public"]["Enums"]["request_tier"];
          district_id: number;
          id?: string;
          is_emergency?: boolean;
          notes?: string | null;
          patient_id: string;
          published_at?: string | null;
          required_at: string;
          status?: Database["public"]["Enums"]["request_status"];
          tier_changed_at?: string | null;
          treating_centre: string;
          units_needed: number;
          updated_at?: string;
        };
        Update: {
          area?: string | null;
          blood_group?: Database["public"]["Enums"]["blood_group"];
          cancel_reason?: string | null;
          closed_at?: string | null;
          component?: string | null;
          created_at?: string;
          created_by?: string;
          current_tier?: Database["public"]["Enums"]["request_tier"];
          district_id?: number;
          id?: string;
          is_emergency?: boolean;
          notes?: string | null;
          patient_id?: string;
          published_at?: string | null;
          required_at?: string;
          status?: Database["public"]["Enums"]["request_status"];
          tier_changed_at?: string | null;
          treating_centre?: string;
          units_needed?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "blood_requests_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "blood_requests_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "blood_requests_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "blood_requests_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patient_cards_for_donor";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "blood_requests_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patients";
            referencedColumns: ["id"];
          },
        ];
      };
      districts: {
        Row: {
          division_id: number;
          id: number;
          name_bn: string;
          name_en: string;
        };
        Insert: {
          division_id: number;
          id: number;
          name_bn: string;
          name_en: string;
        };
        Update: {
          division_id?: number;
          id?: number;
          name_bn?: string;
          name_en?: string;
        };
        Relationships: [
          {
            foreignKeyName: "districts_division_id_fkey";
            columns: ["division_id"];
            isOneToOne: false;
            referencedRelation: "divisions";
            referencedColumns: ["id"];
          },
        ];
      };
      divisions: {
        Row: {
          id: number;
          name_bn: string;
          name_en: string;
        };
        Insert: {
          id: number;
          name_bn: string;
          name_en: string;
        };
        Update: {
          id?: number;
          name_bn?: string;
          name_en?: string;
        };
        Relationships: [];
      };
      donations: {
        Row: {
          confirmed_at: string;
          confirmed_by: string;
          created_at: string;
          donated_on: string;
          donor_id: string;
          id: string;
          patient_id: string;
          request_id: string;
          response_id: string;
          verification: Database["public"]["Enums"]["donation_verification"];
        };
        Insert: {
          confirmed_at?: string;
          confirmed_by: string;
          created_at?: string;
          donated_on: string;
          donor_id: string;
          id?: string;
          patient_id: string;
          request_id: string;
          response_id: string;
          verification: Database["public"]["Enums"]["donation_verification"];
        };
        Update: {
          confirmed_at?: string;
          confirmed_by?: string;
          created_at?: string;
          donated_on?: string;
          donor_id?: string;
          id?: string;
          patient_id?: string;
          request_id?: string;
          response_id?: string;
          verification?: Database["public"]["Enums"]["donation_verification"];
        };
        Relationships: [
          {
            foreignKeyName: "donations_confirmed_by_fkey";
            columns: ["confirmed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "donations_confirmed_by_fkey";
            columns: ["confirmed_by"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "donations_donor_id_fkey";
            columns: ["donor_id"];
            isOneToOne: false;
            referencedRelation: "donor_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "donations_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patient_cards_for_donor";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "donations_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "donations_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "blood_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "donations_response_id_fkey";
            columns: ["response_id"];
            isOneToOne: true;
            referencedRelation: "donor_responses";
            referencedColumns: ["id"];
          },
        ];
      };
      donor_profiles: {
        Row: {
          availability: Database["public"]["Enums"]["donor_availability"];
          available_from: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at: string;
          emergency_available: boolean;
          last_donation_date: string | null;
          searchable: boolean;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          availability?: Database["public"]["Enums"]["donor_availability"];
          available_from?: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at?: string;
          emergency_available?: boolean;
          last_donation_date?: string | null;
          searchable?: boolean;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          availability?: Database["public"]["Enums"]["donor_availability"];
          available_from?: string | null;
          blood_group?: Database["public"]["Enums"]["blood_group"];
          created_at?: string;
          emergency_available?: boolean;
          last_donation_date?: string | null;
          searchable?: boolean;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "donor_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "donor_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      donor_responses: {
        Row: {
          created_at: string;
          donor_id: string;
          donor_reported_donated_at: string | null;
          id: string;
          invited_via: Database["public"]["Enums"]["request_tier"];
          reason: string | null;
          request_id: string;
          responded_at: string | null;
          scheduled_at: string | null;
          status: Database["public"]["Enums"]["response_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          donor_id: string;
          donor_reported_donated_at?: string | null;
          id?: string;
          invited_via: Database["public"]["Enums"]["request_tier"];
          reason?: string | null;
          request_id: string;
          responded_at?: string | null;
          scheduled_at?: string | null;
          status?: Database["public"]["Enums"]["response_status"];
          status_changed_at?: string;
          status_changed_by?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          donor_id?: string;
          donor_reported_donated_at?: string | null;
          id?: string;
          invited_via?: Database["public"]["Enums"]["request_tier"];
          reason?: string | null;
          request_id?: string;
          responded_at?: string | null;
          scheduled_at?: string | null;
          status?: Database["public"]["Enums"]["response_status"];
          status_changed_at?: string;
          status_changed_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "donor_responses_donor_id_fkey";
            columns: ["donor_id"];
            isOneToOne: false;
            referencedRelation: "donor_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "donor_responses_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "blood_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "donor_responses_status_changed_by_fkey";
            columns: ["status_changed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "donor_responses_status_changed_by_fkey";
            columns: ["status_changed_by"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      notification_preferences: {
        Row: {
          push_enabled: boolean;
          type: string;
          user_id: string;
        };
        Insert: {
          push_enabled?: boolean;
          type: string;
          user_id: string;
        };
        Update: {
          push_enabled?: boolean;
          type?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "notification_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      notifications: {
        Row: {
          created_at: string;
          entity_id: string | null;
          entity_type: string | null;
          id: string;
          params: NonNullable<Json>;
          pushed_at: string | null;
          read_at: string | null;
          type: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string | null;
          id?: string;
          params?: NonNullable<Json>;
          pushed_at?: string | null;
          read_at?: string | null;
          type: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string | null;
          id?: string;
          params?: NonNullable<Json>;
          pushed_at?: string | null;
          read_at?: string | null;
          type?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      patient_donor_connections: {
        Row: {
          created_at: string;
          donor_id: string;
          end_reason: string | null;
          id: string;
          initiated_by: Database["public"]["Enums"]["connection_initiator"];
          patient_id: string;
          status: Database["public"]["Enums"]["connection_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          tier: Database["public"]["Enums"]["connection_tier"];
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          donor_id: string;
          end_reason?: string | null;
          id?: string;
          initiated_by: Database["public"]["Enums"]["connection_initiator"];
          patient_id: string;
          status?: Database["public"]["Enums"]["connection_status"];
          status_changed_at?: string;
          status_changed_by?: string | null;
          tier?: Database["public"]["Enums"]["connection_tier"];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          donor_id?: string;
          end_reason?: string | null;
          id?: string;
          initiated_by?: Database["public"]["Enums"]["connection_initiator"];
          patient_id?: string;
          status?: Database["public"]["Enums"]["connection_status"];
          status_changed_at?: string;
          status_changed_by?: string | null;
          tier?: Database["public"]["Enums"]["connection_tier"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "patient_donor_connections_donor_id_fkey";
            columns: ["donor_id"];
            isOneToOne: false;
            referencedRelation: "donor_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "patient_donor_connections_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patient_cards_for_donor";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "patient_donor_connections_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "patient_donor_connections_status_changed_by_fkey";
            columns: ["status_changed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "patient_donor_connections_status_changed_by_fkey";
            columns: ["status_changed_by"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      patient_managers: {
        Row: {
          created_at: string;
          is_primary: boolean;
          patient_id: string;
          relation: Database["public"]["Enums"]["manager_relation"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          is_primary?: boolean;
          patient_id: string;
          relation: Database["public"]["Enums"]["manager_relation"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          is_primary?: boolean;
          patient_id?: string;
          relation?: Database["public"]["Enums"]["manager_relation"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "patient_managers_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patient_cards_for_donor";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "patient_managers_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "patients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "patient_managers_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "patient_managers_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      patients: {
        Row: {
          archived_at: string | null;
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at: string;
          created_by: string;
          display_name: string;
          district_id: number;
          id: string;
          invite_code: string;
          next_transfusion_date: string | null;
          show_area: boolean;
          show_next_transfusion: boolean;
          show_thalassemia_type: boolean;
          show_treating_centre: boolean;
          thalassemia_type: string | null;
          treating_centre: string | null;
          updated_at: string;
        };
        Insert: {
          archived_at?: string | null;
          area?: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at?: string;
          created_by: string;
          display_name: string;
          district_id: number;
          id?: string;
          invite_code: string;
          next_transfusion_date?: string | null;
          show_area?: boolean;
          show_next_transfusion?: boolean;
          show_thalassemia_type?: boolean;
          show_treating_centre?: boolean;
          thalassemia_type?: string | null;
          treating_centre?: string | null;
          updated_at?: string;
        };
        Update: {
          archived_at?: string | null;
          area?: string | null;
          blood_group?: Database["public"]["Enums"]["blood_group"];
          created_at?: string;
          created_by?: string;
          display_name?: string;
          district_id?: number;
          id?: string;
          invite_code?: string;
          next_transfusion_date?: string | null;
          show_area?: boolean;
          show_next_transfusion?: boolean;
          show_thalassemia_type?: boolean;
          show_treating_centre?: boolean;
          thalassemia_type?: string | null;
          treating_centre?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "patients_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "patients_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "patients_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          area: string | null;
          created_at: string;
          deleted_at: string | null;
          display_name: string;
          district_id: number | null;
          language: string;
          onboarded_at: string | null;
          phone: string | null;
          preferred_contact: Database["public"]["Enums"]["contact_method"];
          share_contact_on_accept: boolean;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          area?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          display_name: string;
          district_id?: number | null;
          language?: string;
          onboarded_at?: string | null;
          phone?: string | null;
          preferred_contact?: Database["public"]["Enums"]["contact_method"];
          share_contact_on_accept?: boolean;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          area?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          display_name?: string;
          district_id?: number | null;
          language?: string;
          onboarded_at?: string | null;
          phone?: string | null;
          preferred_contact?: Database["public"]["Enums"]["contact_method"];
          share_contact_on_accept?: boolean;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
        ];
      };
      push_tokens: {
        Row: {
          platform: string;
          token: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          platform: string;
          token: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          platform?: string;
          token?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "push_tokens_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "push_tokens_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      user_roles: {
        Row: {
          created_at: string;
          granted_by: string | null;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          granted_by?: string | null;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          granted_by?: string | null;
          role?: Database["public"]["Enums"]["app_role"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_roles_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "user_roles_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "user_roles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "user_roles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
    };
    Views: {
      patient_cards_for_donor: {
        Row: {
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"] | null;
          display_name: string | null;
          district_id: number | null;
          id: string | null;
          next_transfusion_date: string | null;
          thalassemia_type: string | null;
          treating_centre: string | null;
        };
        Insert: {
          area?: never;
          blood_group?: Database["public"]["Enums"]["blood_group"] | null;
          display_name?: string | null;
          district_id?: number | null;
          id?: string | null;
          next_transfusion_date?: never;
          thalassemia_type?: never;
          treating_centre?: never;
        };
        Update: {
          area?: never;
          blood_group?: Database["public"]["Enums"]["blood_group"] | null;
          display_name?: string | null;
          district_id?: number | null;
          id?: string | null;
          next_transfusion_date?: never;
          thalassemia_type?: never;
          treating_centre?: never;
        };
        Relationships: [
          {
            foreignKeyName: "patients_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
        ];
      };
      public_profiles: {
        Row: {
          display_name: string | null;
          user_id: string | null;
        };
        Insert: {
          display_name?: string | null;
          user_id?: string | null;
        };
        Update: {
          display_name?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      add_role: {
        Args: { role: Database["public"]["Enums"]["app_role"] };
        Returns: undefined;
      };
      bd_date: { Args: { ts: string }; Returns: string };
      cancel_blood_request: {
        Args: { reason?: string; request_id: string };
        Returns: {
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          cancel_reason: string | null;
          closed_at: string | null;
          component: string | null;
          created_at: string;
          created_by: string;
          current_tier: Database["public"]["Enums"]["request_tier"];
          district_id: number;
          id: string;
          is_emergency: boolean;
          notes: string | null;
          patient_id: string;
          published_at: string | null;
          required_at: string;
          status: Database["public"]["Enums"]["request_status"];
          tier_changed_at: string | null;
          treating_centre: string;
          units_needed: number;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "blood_requests";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      cancel_connection_request: {
        Args: { connection_id: string };
        Returns: {
          created_at: string;
          donor_id: string;
          end_reason: string | null;
          id: string;
          initiated_by: Database["public"]["Enums"]["connection_initiator"];
          patient_id: string;
          status: Database["public"]["Enums"]["connection_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          tier: Database["public"]["Enums"]["connection_tier"];
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patient_donor_connections";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      complete_onboarding: {
        Args: {
          area?: string;
          display_name: string;
          district_id?: number;
          language?: string;
          phone?: string;
          roles: Database["public"]["Enums"]["app_role"][];
          share_contact_on_accept?: boolean;
        };
        Returns: {
          area: string | null;
          created_at: string;
          deleted_at: string | null;
          display_name: string;
          district_id: number | null;
          language: string;
          onboarded_at: string | null;
          phone: string | null;
          preferred_contact: Database["public"]["Enums"]["contact_method"];
          share_contact_on_accept: boolean;
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "profiles";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      confirm_donation: {
        Args: { donated_on: string; response_id: string };
        Returns: {
          confirmed_at: string;
          confirmed_by: string;
          created_at: string;
          donated_on: string;
          donor_id: string;
          id: string;
          patient_id: string;
          request_id: string;
          response_id: string;
          verification: Database["public"]["Enums"]["donation_verification"];
        };
        SetofOptions: {
          from: "*";
          to: "donations";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_blood_request: {
        Args: {
          area?: string;
          blood_group?: Database["public"]["Enums"]["blood_group"];
          component?: string;
          district_id: number;
          is_emergency?: boolean;
          notes?: string;
          patient_id: string;
          required_at: string;
          treating_centre: string;
          units_needed?: number;
        };
        Returns: {
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          cancel_reason: string | null;
          closed_at: string | null;
          component: string | null;
          created_at: string;
          created_by: string;
          current_tier: Database["public"]["Enums"]["request_tier"];
          district_id: number;
          id: string;
          is_emergency: boolean;
          notes: string | null;
          patient_id: string;
          published_at: string | null;
          required_at: string;
          status: Database["public"]["Enums"]["request_status"];
          tier_changed_at: string | null;
          treating_centre: string;
          units_needed: number;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "blood_requests";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_patient: {
        Args: {
          area?: string;
          as_self?: boolean;
          blood_group: Database["public"]["Enums"]["blood_group"];
          display_name: string;
          district_id: number;
          next_transfusion_date?: string;
          show_area?: boolean;
          show_next_transfusion?: boolean;
          show_thalassemia_type?: boolean;
          show_treating_centre?: boolean;
          thalassemia_type?: string;
          treating_centre?: string;
        };
        Returns: {
          archived_at: string | null;
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at: string;
          created_by: string;
          display_name: string;
          district_id: number;
          id: string;
          invite_code: string;
          next_transfusion_date: string | null;
          show_area: boolean;
          show_next_transfusion: boolean;
          show_thalassemia_type: boolean;
          show_treating_centre: boolean;
          thalassemia_type: string | null;
          treating_centre: string | null;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patients";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      dearmor: { Args: { "": string }; Returns: string };
      enqueue_notification: {
        Args: {
          p_entity_id: string;
          p_entity_type: string;
          p_params?: Json;
          p_type: string;
          p_user_id: string;
        };
        Returns: undefined;
      };
      gen_random_uuid: { Args: Record<PropertyKey, never>; Returns: string };
      gen_salt: { Args: { "": string }; Returns: string };
      generate_invite_code: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      get_connection_parties: {
        Args: { connection_id: string };
        Returns: {
          donor_availability: Database["public"]["Enums"]["donor_availability"];
          donor_blood_group: Database["public"]["Enums"]["blood_group"];
          donor_display_name: string;
          patient_blood_group: Database["public"]["Enums"]["blood_group"];
          patient_display_name: string;
          patient_district_id: number;
        }[];
      };
      get_request_for_donor: {
        Args: { request_id: string };
        Returns: {
          area: string;
          blood_group: Database["public"]["Enums"]["blood_group"];
          component: string;
          district_id: number;
          id: string;
          is_emergency: boolean;
          my_response_status: Database["public"]["Enums"]["response_status"];
          patient_display_name: string;
          required_at: string;
          status: Database["public"]["Enums"]["request_status"];
          treating_centre: string;
          units_needed: number;
        }[];
      };
      get_response_contact: {
        Args: { response_id: string };
        Returns: {
          donor_phone: string;
          donor_preferred_contact: Database["public"]["Enums"]["contact_method"];
          manager_phone: string;
          manager_preferred_contact: Database["public"]["Enums"]["contact_method"];
        }[];
      };
      has_role: {
        Args: { target_role: Database["public"]["Enums"]["app_role"] };
        Returns: boolean;
      };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_connected_donor: {
        Args: { target_patient_id: string };
        Returns: boolean;
      };
      is_invited_donor: {
        Args: { target_request_id: string };
        Returns: boolean;
      };
      is_patient_manager: {
        Args: { target_patient_id: string };
        Returns: boolean;
      };
      manages_connected_donor: {
        Args: { target_donor_id: string };
        Returns: boolean;
      };
      mark_all_notifications_read: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      mark_notification_read: {
        Args: { id: string };
        Returns: {
          created_at: string;
          entity_id: string | null;
          entity_type: string | null;
          id: string;
          params: NonNullable<Json>;
          pushed_at: string | null;
          read_at: string | null;
          type: string;
          user_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "notifications";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      pgp_armor_headers: {
        Args: { "": string };
        Returns: Record<string, unknown>[];
      };
      process_request_timers: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      publish_blood_request: {
        Args: { request_id: string };
        Returns: {
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          cancel_reason: string | null;
          closed_at: string | null;
          component: string | null;
          created_at: string;
          created_by: string;
          current_tier: Database["public"]["Enums"]["request_tier"];
          district_id: number;
          id: string;
          is_emergency: boolean;
          notes: string | null;
          patient_id: string;
          published_at: string | null;
          required_at: string;
          status: Database["public"]["Enums"]["request_status"];
          tier_changed_at: string | null;
          treating_centre: string;
          units_needed: number;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "blood_requests";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      recompute_request_status: {
        Args: { request_id: string };
        Returns: undefined;
      };
      register_push_token: {
        Args: { platform: string; token: string };
        Returns: {
          platform: string;
          token: string;
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "push_tokens";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      report_donated: {
        Args: { response_id: string };
        Returns: {
          created_at: string;
          donor_id: string;
          donor_reported_donated_at: string | null;
          id: string;
          invited_via: Database["public"]["Enums"]["request_tier"];
          reason: string | null;
          request_id: string;
          responded_at: string | null;
          scheduled_at: string | null;
          status: Database["public"]["Enums"]["response_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "donor_responses";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      request_connection_by_code: {
        Args: { invite_code: string };
        Returns: {
          created_at: string;
          donor_id: string;
          end_reason: string | null;
          id: string;
          initiated_by: Database["public"]["Enums"]["connection_initiator"];
          patient_id: string;
          status: Database["public"]["Enums"]["connection_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          tier: Database["public"]["Enums"]["connection_tier"];
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patient_donor_connections";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      respond_connection: {
        Args: {
          accept: boolean;
          connection_id: string;
          tier?: Database["public"]["Enums"]["connection_tier"];
        };
        Returns: {
          created_at: string;
          donor_id: string;
          end_reason: string | null;
          id: string;
          initiated_by: Database["public"]["Enums"]["connection_initiator"];
          patient_id: string;
          status: Database["public"]["Enums"]["connection_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          tier: Database["public"]["Enums"]["connection_tier"];
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patient_donor_connections";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      respond_to_request: {
        Args: { accept: boolean; reason?: string; response_id: string };
        Returns: {
          created_at: string;
          donor_id: string;
          donor_reported_donated_at: string | null;
          id: string;
          invited_via: Database["public"]["Enums"]["request_tier"];
          reason: string | null;
          request_id: string;
          responded_at: string | null;
          scheduled_at: string | null;
          status: Database["public"]["Enums"]["response_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "donor_responses";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      rotate_invite_code: {
        Args: { patient_id: string };
        Returns: {
          archived_at: string | null;
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at: string;
          created_by: string;
          display_name: string;
          district_id: number;
          id: string;
          invite_code: string;
          next_transfusion_date: string | null;
          show_area: boolean;
          show_next_transfusion: boolean;
          show_thalassemia_type: boolean;
          show_treating_centre: boolean;
          thalassemia_type: string | null;
          treating_centre: string | null;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patients";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      schedule_donation: {
        Args: { response_id: string; scheduled_at: string };
        Returns: {
          created_at: string;
          donor_id: string;
          donor_reported_donated_at: string | null;
          id: string;
          invited_via: Database["public"]["Enums"]["request_tier"];
          reason: string | null;
          request_id: string;
          responded_at: string | null;
          scheduled_at: string | null;
          status: Database["public"]["Enums"]["response_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "donor_responses";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      set_connection_status: {
        Args: {
          connection_id: string;
          new_status: Database["public"]["Enums"]["connection_status"];
          reason?: string;
        };
        Returns: {
          created_at: string;
          donor_id: string;
          end_reason: string | null;
          id: string;
          initiated_by: Database["public"]["Enums"]["connection_initiator"];
          patient_id: string;
          status: Database["public"]["Enums"]["connection_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          tier: Database["public"]["Enums"]["connection_tier"];
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patient_donor_connections";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      set_connection_tier: {
        Args: {
          connection_id: string;
          tier: Database["public"]["Enums"]["connection_tier"];
        };
        Returns: {
          created_at: string;
          donor_id: string;
          end_reason: string | null;
          id: string;
          initiated_by: Database["public"]["Enums"]["connection_initiator"];
          patient_id: string;
          status: Database["public"]["Enums"]["connection_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          tier: Database["public"]["Enums"]["connection_tier"];
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patient_donor_connections";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      shares_active_connection: {
        Args: { other_user_id: string };
        Returns: boolean;
      };
      update_blood_request: {
        Args: {
          area?: string;
          blood_group?: Database["public"]["Enums"]["blood_group"];
          component?: string;
          district_id?: number;
          is_emergency?: boolean;
          notes?: string;
          request_id: string;
          required_at?: string;
          treating_centre?: string;
          units_needed?: number;
        };
        Returns: {
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          cancel_reason: string | null;
          closed_at: string | null;
          component: string | null;
          created_at: string;
          created_by: string;
          current_tier: Database["public"]["Enums"]["request_tier"];
          district_id: number;
          id: string;
          is_emergency: boolean;
          notes: string | null;
          patient_id: string;
          published_at: string | null;
          required_at: string;
          status: Database["public"]["Enums"]["request_status"];
          tier_changed_at: string | null;
          treating_centre: string;
          units_needed: number;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "blood_requests";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      update_patient: {
        Args: {
          area?: string;
          blood_group?: Database["public"]["Enums"]["blood_group"];
          display_name?: string;
          district_id?: number;
          next_transfusion_date?: string;
          patient_id: string;
          show_area?: boolean;
          show_next_transfusion?: boolean;
          show_thalassemia_type?: boolean;
          show_treating_centre?: boolean;
          thalassemia_type?: string;
          treating_centre?: string;
        };
        Returns: {
          archived_at: string | null;
          area: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at: string;
          created_by: string;
          display_name: string;
          district_id: number;
          id: string;
          invite_code: string;
          next_transfusion_date: string | null;
          show_area: boolean;
          show_next_transfusion: boolean;
          show_thalassemia_type: boolean;
          show_treating_centre: boolean;
          thalassemia_type: string | null;
          treating_centre: string | null;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "patients";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      upsert_donor_profile: {
        Args: {
          availability?: Database["public"]["Enums"]["donor_availability"];
          available_from?: string;
          blood_group: Database["public"]["Enums"]["blood_group"];
          emergency_available?: boolean;
          searchable?: boolean;
        };
        Returns: {
          availability: Database["public"]["Enums"]["donor_availability"];
          available_from: string | null;
          blood_group: Database["public"]["Enums"]["blood_group"];
          created_at: string;
          emergency_available: boolean;
          last_donation_date: string | null;
          searchable: boolean;
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "donor_profiles";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      withdraw_response: {
        Args: { reason?: string; response_id: string };
        Returns: {
          created_at: string;
          donor_id: string;
          donor_reported_donated_at: string | null;
          id: string;
          invited_via: Database["public"]["Enums"]["request_tier"];
          reason: string | null;
          request_id: string;
          responded_at: string | null;
          scheduled_at: string | null;
          status: Database["public"]["Enums"]["response_status"];
          status_changed_at: string;
          status_changed_by: string | null;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "donor_responses";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      write_audit: {
        Args: {
          p_action: string;
          p_new_data: Json;
          p_old_data: Json;
          p_row_id: string;
          p_table_name: string;
        };
        Returns: undefined;
      };
    };
    Enums: {
      app_role: "patient" | "guardian" | "donor" | "organization" | "admin";
      blood_group:
        | "A_POS"
        | "A_NEG"
        | "B_POS"
        | "B_NEG"
        | "AB_POS"
        | "AB_NEG"
        | "O_POS"
        | "O_NEG";
      connection_initiator: "patient_side" | "donor";
      connection_status:
        | "requested"
        | "active"
        | "declined"
        | "cancelled"
        | "paused"
        | "removed";
      connection_tier: "regular" | "backup";
      contact_method: "phone" | "whatsapp" | "in_app";
      donation_verification: "guardian_confirmed" | "org_verified";
      donor_availability: "available" | "unavailable" | "paused";
      manager_relation: "self" | "guardian";
      request_status:
        | "draft"
        | "open"
        | "responding"
        | "partially_fulfilled"
        | "fulfilled"
        | "cancelled"
        | "expired";
      request_tier: "regular" | "backup" | "broad";
      response_status:
        | "invited"
        | "accepted"
        | "declined"
        | "donation_pending"
        | "completed"
        | "cancelled"
        | "expired";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      app_role: ["patient", "guardian", "donor", "organization", "admin"],
      blood_group: [
        "A_POS",
        "A_NEG",
        "B_POS",
        "B_NEG",
        "AB_POS",
        "AB_NEG",
        "O_POS",
        "O_NEG",
      ],
      connection_initiator: ["patient_side", "donor"],
      connection_status: [
        "requested",
        "active",
        "declined",
        "cancelled",
        "paused",
        "removed",
      ],
      connection_tier: ["regular", "backup"],
      contact_method: ["phone", "whatsapp", "in_app"],
      donation_verification: ["guardian_confirmed", "org_verified"],
      donor_availability: ["available", "unavailable", "paused"],
      manager_relation: ["self", "guardian"],
      request_status: [
        "draft",
        "open",
        "responding",
        "partially_fulfilled",
        "fulfilled",
        "cancelled",
        "expired",
      ],
      request_tier: ["regular", "backup", "broad"],
      response_status: [
        "invited",
        "accepted",
        "declined",
        "donation_pending",
        "completed",
        "cancelled",
        "expired",
      ],
    },
  },
} as const;
