// Generated by `npx supabase gen types typescript --local > src/lib/database.types.ts`.
// Phase 0 has no application tables yet, so this is a minimal placeholder —
// regenerate it after the first schema-bearing migration lands.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
