#!/usr/bin/env bash
# Generates docs/API.md from the local database: every function the app
# (role `authenticated`) may call, with its signature, return type, who may
# call it and the error codes it raises. Re-run after changing migrations:
#   npx supabase start && scripts/gen-api-docs.sh
set -euo pipefail

DB_URL="${DB_URL:-postgresql://postgres:postgres@127.0.0.1:54322/postgres}"
OUT="${1:-docs/API.md}"

{
  cat <<'EOF'
# API reference (Supabase RPCs)

_Generated by `scripts/gen-api-docs.sh` from the database. Do not edit by
hand._

The app talks to Supabase with the user's JWT. Reads of plain tables go
through RLS (ARCHITECTURE §8); every state change goes through one of the
functions below (D2/D3), called with `supabase.rpc(name, { args })`.
Named arguments use the parameter names shown.

- **Errors**: `code = P0001`, `message = <error_code>`; the app shows
  `errors.<error_code>` from the locale files (`src/lib/errors.ts`).
- **Who**: every function re-checks authorization itself. "Admin" functions
  require the `admin` role; "Organization staff" functions require
  membership of a verified organization; "RLS helper" functions are used by
  policies and views and return booleans only.
- Internal functions (notifications, audit, timers, triggers) are not
  callable by clients and are not listed (tests/80_function_privileges).

EOF
  psql "$DB_URL" -X -q -At <<'SQL'
with fns as (
  select
    p.proname as name,
    pg_get_function_arguments(p.oid) as args,
    pg_get_function_result(p.oid) as result,
    case
      when p.proname in ('has_role', 'is_admin', 'is_patient_manager', 'manages_connected_donor',
                         'is_connected_donor', 'is_invited_donor', 'shares_active_connection',
                         'manages_request_with_donor', 'is_blocked_between',
                         'has_accepted_community_guidelines', 'is_active_organization_member')
        then '4. RLS helpers'
      when p.proname like 'admin\_%' or p.proname in ('list_moderation_queue', 'moderate_community_content', 'remove_appreciation')
        then '3. Admin'
      when p.proname like 'org\_%' then '2. Organization staff'
      else '1. Signed-in users'
    end as audience,
    (
      select string_agg(distinct m[1], ', ' order by m[1])
      from regexp_matches(p.prosrc, 'message\s*=\s*(?:case[^;]*?then\s*)?''([a-z_]+)''', 'g') m
    ) as errors,
    (
      select string_agg(distinct m[1], ', ' order by m[1])
      from regexp_matches(p.prosrc, 'else\s+''([a-z_]+)''\s+end', 'g') m
    ) as extra_errors
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and has_function_privilege('authenticated', p.oid, 'execute')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
)
select string_agg(section, E'\n' order by audience)
from (
  select audience,
    '## ' || substr(audience, 4) || E'\n\n' ||
    string_agg(
      '### `' || name || '`' || E'\n\n' ||
      '```' || E'\n' || name || '(' || args || ')' || E'\n→ ' || result || E'\n```\n' ||
      case when coalesce(errors, extra_errors) is not null
        then E'\nErrors: `' || replace(concat_ws(', ', errors, extra_errors), ', ', '`, `') || E'`\n'
        else '' end,
      E'\n' order by name
    ) as section
  from fns
  group by audience
) s;
SQL
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^### ' "$OUT") functions)"
npx prettier --write "$OUT" >/dev/null 2>&1 || true
